			$(".p1").slideUp();
			$(".p2").slideUp();
			$(".p3").slideUp();
			$(".p4").slideUp();
			$(".p5").slideUp();
			$(document).ready(function(){
				$(".g1").click(function(){
					$(".p2").slideUp();
					$(".p3").slideUp();
					$(".p4").slideUp();
					$(".p5").slideUp();
					$(".p1").slideDown(2000);
				});
				$(".g2").click(function(){
					$(".p1").slideUp();
					$(".p3").slideUp();
					$(".p4").slideUp();
					$(".p5").slideUp();
					$(".p2").slideDown(2000);
				});
				$(".g3").click(function(){
					$(".p2").slideUp();
					$(".p1").slideUp();
					$(".p4").slideUp();
					$(".p5").slideUp();
					$(".p3").slideDown(2000);
				});
				$(".g4").click(function(){
					$(".p2").slideUp();
					$(".p3").slideUp();
					$(".p1").slideUp();
					$(".p5").slideUp();
					$(".p4").slideDown(2000);
				});
				$(".g5").click(function(){
					$(".p2").slideUp();
					$(".p3").slideUp();
					$(".p4").slideUp();
					$(".p1").slideUp();
					$(".p5").slideDown(2000);
				});
			});
